---
- hosts: all
  gather_facts: False
  pre_tasks:
    - name: Install Python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  tasks:
    - group:
        name: cocktailbot
        state: present

    - name: Create default user
      user:
        name: cocktailbot
        comment: "Cocktail Bot"
        group: cocktailbot

    - file:
        path: /home/cocktailbot/go_workspace
        state: directory
        mode: 0755

    - name: Download Go
      get_url:
        url: https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
        dest: /home/cocktailbot
      register: download_go

    - stat:
        path: /home/cocktailbot/go1.8.linux-amd64.tar.gz
        checksum_algorithm: sha256

    - name: Extract Go
      unarchive:
        src: /home/cocktailbot/go1.8.linux-amd64.tar.gz
        dest: /home/cocktailbot/
        remote_src: true

    - name: Move Go into place
      command: mv /home/cocktailbot/go /usr/local creates=/usr/local/go

    - name: Move bash_profile
      copy:
        src: files/.bash_profile
        dest: /home/cocktailbot
        owner: cocktailbot
        group: cocktailbot
        mode: 0644

    - apt_repository:
        repo: 'ppa:webupd8team/java'
        update_cache: yes

    - name: Agree to oracle license
      debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

    - name: Install Java 8
      apt:
        name: oracle-java8-installer
        state: latest
        force: yes

    - apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

    - apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
        update_cache: yes

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: latest

    - copy:
        src: files/elasticsearch/elasticsearch.yml
        dest: /etc/elasticsearch

    - copy:
        src: files/elasticsearch/jvm.options
        dest: /etc/elasticsearch

    - name: Create swap file
      shell: |
        fallocate -l 1G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile
        creates=/swapfile

    - service:
        name: elasticsearch
        enabled: yes
        state: started

    - debug:
        msg="Go was downloaded"
      when: download_go|changed
